### ISSUE TITLE
Prompt user to refresh the app, upon detecting new version

### ISSUE THREAD

**Issue by lcb931023** [HeliosInteractive/helios-vue#7]
Currently, the service worker requires two refreshes to update the app. This is a behavior that tends to be forgotten by Ops.

Is there a way the service worker can detect that something has changed upon first refresh, then prompt user to refresh again?

bonus: have a button that runs `location.reload()` on the prompt.

**Comment by adammcfadden** [comment]
I think that simple solution for this right now is to have service worker off by default. Perhaps, if we move this to a vue-cli project we can have a cli option to include it or not. I think for now I will just comment out where webpack inserts it in the index.html, and add instructions to the README for how to enable it.

**Comment by halfwizard** [comment]
Archiving this repo. Will not do.
